version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/Watch
  docker:
    - image: circleci/golang:latest

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/golang/lint/golint
      - run: dep ensure
      - run: ./gok.sh


  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go build
      - run: docker build -t quay.io/weaveworks/watch -t quay.io/weaveworks/watch-$(./image-tag) .
      - deploy:
          name: push image
          command: |
            docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker push "quay.io/weaveworks/watch:$(./image-tag)"
              docker push "quay.io/weaveworks/watch"
            fi


workflows:
  version: 2
  build_deploy:
    jobs:
      - tests
      - build
